name: JSON to M3U

on:
  push:
    paths:
      - "jiotv.json"
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Convert JSON â†’ M3U
        run: node json-to-m3u.js

      - name: Commit M3U
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add jiotv.m3u
          git commit -m "Auto update M3U"
          git push
